environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor-ci\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_PY: "35"
      ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda update -yq --all
  - conda install -yq conda-build jinja2

build: false

test_script:
  - "%CMD_IN_ENV% activate base"
  - "%CMD_IN_ENV% pip install git+https://github.com/mosdef-hub/mbuild.git"
  - "%CMD_IN_ENV% py.test -v --cov=foyer --cov-report= --pyargs foyer"
