environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor-ci\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_PY: "27"
      ARCH: "64"
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_PY: "35"
      ARCH: "64"
    - PYTHON: "C:\\Miniconda36-x64"
      CONDA_PY: "36"
      ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda update -yq --all
  - conda install -yq conda-build jinja2
  - conda create -n test-environment python=%PYTHON_VERSION% --file requirements-dev.txt
  - activate test-environment
  - pip install git+https://github.com/mosdef-hub/mbuild.git
  - pip install -e .

build: false

test_script:
  - "%CMD_IN_ENV% python -m pytest -v --cov=foyer --cov-report= --pyargs foyer"
