name: foyer-dev
channels:
  - conda-forge
  - omnia
dependencies:
  - bump2version
  - codecov
  - lark
  - lxml
  - mbuild>=0.17
  - treelib
  - gmso
  - networkx>=2.5
  - openmm
  - parmed>=3.4.3
  - pip
  - pytest
  - pytest-azurepipelines
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - python>=3.9
  - requests
  - requests-mock
